### PR TITLE
feat(YouTube): support `v18.29.38`

### PR DESCRIPTION
**Pull request by oSumAtrIX**
# TODO

- [ ] `Hide breaking news` succeeding but not working (Unknown)
- [x] `Disable fullscreen panels` failing (Due to fingerprint/Structural changes in YouTube)
- [x] `Return YouTube Dislike` failing (Due to fingerprint)

### CODE REVIEW

**Comment by johnconner122** [comment]
> It appears 18.29 changed the behavior so full screen panel no longer shows unless the comments are already opened?
> 
> Unpatched 18.23:
> 
> ```
>         if (ac(1) && (coordinatorLayout2 = this.x) != null) {
>             coordinatorLayout2.setVisibility(true == this.i ? 0 : 8);     // 0 == View.Visible, 8 == View.Gone
>         }
> ```
> 
> Patched 18.23:
> 
> ```
>         if (ac(1) && (coordinatorLayout2 = this.x) != null) {
>             coordinatorLayout2.setVisibility(FullscreenPanelsRemoverPatch.getFullscreenPanelsVisibility());
>         }
> ```
> 
> Unpatched 18.29:
> 
> ```
>         if (ac(1) && (coordinatorLayout2 = this.v) != null) {
>             coordinatorLayout2.setVisibility(8);       // 8 == View.Gone
>         }
> ```
> 
> So the patch needs to be altered so it hides the panel even if comments is already opened (but is that useful?), or the patch needs to be removed as it's no longer needed with 18.29+
> 
> Or am I overlooking something here?

How about [this one](https://github.com/inotia00/revanced-patches/tree/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/fullscreen/fullscreenpanels)?

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios Entwring fullscreen is considered more a way to dismiss everything in favour of watching the current playing video, yet, YouTube decides to show the comments assuming the intention of going into fullscreen while watching comments is to continue watching them. If ReVanced gave the ability to set the visibility to GONE, but YouTube does it by default now, the patch can be removed, though, currently the fullscreen panels are still hidden even if yougo into fullscreen while viewing the comments. If this behavior has been altered in recent versions, the patch may be adjusted to bring bacj the current behavior

**Comment by oSumAtrIX** [comment]
The most likely scenario I can imagine when scrolling through the comments while the video is playing is if you are less interested in the current video andd curious to check what others comment about, or maybe you are currently commenting. Having to close the comments, then enter fullscreen or vice versa. I can't imagine when you would want to enter fullscreen, an obvious intention to watch the video at full screen but not be able to watch the video at fullscreen because of the comments pooping out, when they were open already, at a time you intended them to be open next to your playing video

**Comment by oSumAtrIX** [comment]
I personally check out the comments often and then switch back into fullscreen when I want to continue watching the video, if the comments are still visible, I have to close them in addition to that. I believe this behaviour will obstruct other people, but I'd say we can ignore it for now, watch for user input, then decide at a later time. I marked it as done.

**Comment by johnconner122** [comment]
> Does hide breaking news working with 18.23.35? I see some users saying the patch isn't working for them.
> 
> YouTube doesn't seem to show news for my tiny country (no news is good news?), so I can't try to identify litho or layout components for it.

I only see them in Incognito mode.

**Comment by oSumAtrIX** [comment]
I can see them on my end, but I have not checked if they even are litho components.

**Comment by johnconner122** [comment]
> I can see them on my end, but I have not checked if they even are litho components.

`horizontal_video_shelf` seems to be blocking `breaking news shelf`, but it also filters `library_recent_shelf`, but it is added to exceptions in `LayoutComponents`, so problem solved.

**Comment by johnconner122** [comment]
Never mind, playlists in library are hidden by it.

**Comment by johnconner122** [comment]
But we can add a check for only allowing filtering in home feed?

**Comment by oSumAtrIX** [comment]
Yes, there is technically a way to check for the current page you are on (home/library), then enable the filter or not depending on it.

**Comment by kazimmt** [comment]
Breaking News Not Hiding

These may help:
- https://github.com/inotia00/ReVanced_Extended/issues/575
- https://github.com/inotia00/ReVanced_Extended/issues/1142
- https://github.com/inotia00/revanced-patches/tree/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/general/suggestions

**Comment by oSumAtrIX** [comment]
There is no difference.

**Comment by johnconner122** [comment]
I think this is the one:
https://github.com/inotia00/revanced-integrations/blob/revanced-extended/app/src/main/java/app/revanced/integrations/patches/ads/NavBarIndexFilter.java

**Comment by 0xrxL** [comment]
> Never mind, playlists in library are hidden by it.

I already developed an efficient way to hide ```horizontal_video_shelf``` only outside of library tab. It's a bit tricky, but It hasn't given me any problems so far.

I'll add you as collaborator on uPatcher to implement this (if you're interested). The method name inside uPatcher project is ```Horizontal_Video_Shelf_Removal()```

**Comment by 0xrxL** [comment]
Done...now also @LisoUseInAIKyrios is a collaborator of uPatcher (I developed other 1/2 personal patches that may interest you).

**Comment by johnconner122** [comment]
> > Never mind, playlists in library are hidden by it.
> 
> I already developed an efficient way to hide `horizontal_video_shelf` only outside of library tab. It's a bit tricky, but It hasn't given me any problems so far.
> 
> I'll add you as collaborator on uPatcher to implement this (if you're interested). The method name inside uPatcher project is `Horizontal_Video_Shelf_Removal()`

Seems to be similar to [inotia00](https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/utils/navbarindex/patch/NavBarIndexHookPatch.kt)'s version.

**Comment by 0xrxL** [comment]
> > > Never mind, playlists in library are hidden by it.
> > 
> > 
> > I already developed an efficient way to hide `horizontal_video_shelf` only outside of library tab. It's a bit tricky, but It hasn't given me any problems so far.
> > I'll add you as collaborator on uPatcher to implement this (if you're interested). The method name inside uPatcher project is `Horizontal_Video_Shelf_Removal()`
> 
> Seems to be similar to [inotia00](https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/utils/navbarindex/patch/NavBarIndexHookPatch.kt)'s version.

Yeah...he already had access to my repository and asked me about how the patch worked. I believe he later implemented it on his repo too.

**Comment by 0xrxL** [comment]
> > > Never mind, playlists in library are hidden by it.
> > 
> > 
> > I already developed an efficient way to hide `horizontal_video_shelf` only outside of library tab. It's a bit tricky, but It hasn't given me any problems so far.
> > I'll add you as collaborator on uPatcher to implement this (if you're interested). The method name inside uPatcher project is `Horizontal_Video_Shelf_Removal()`
> 
> Seems to be similar to [inotia00](https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/utils/navbarindex/patch/NavBarIndexHookPatch.kt)'s version.

Give a look to the patch ```Search_Suggestion_Removal``` too, to remove the trending results down to the video search box.

**Pull request closed without merging**
