### PR TITLE
fix: remove unnecessary version constraints in debugging patch

### PR DESCRIPTION
**Pull request by bogadana**
this patch is also compatible with every android app but there doesnt seem to be a good way to specify that

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
The package name constraint can also be removed if necessary: https://github.com/revanced/revanced-cli/blob/387b6bd0163d660cebd31fc2126c0c57fbae7470/src/main/kotlin/app/revanced/utils/patcher/Patcher.kt#L38

**Comment by bogadana** [comment]
still i think generating warnings when nothing is wrong is undesirable

**Comment by oSumAtrIX** [comment]
You could remove the package constraint as previously said, this will produce an expected warning though.

**Comment by bogadana** [comment]
I can't because `Null can not be a value of a non-null type Array<Package>`

**Comment by oSumAtrIX** [comment]
About the nullability of the annotation properties, if possible, could you PR a proper implementation? Sometimes you have to use the empty array initializer when not required.

**Comment by oSumAtrIX** [comment]
> I can't because `Null can not be a value of a non-null type Array<Package>`

You have to use an empty array

**Comment by oSumAtrIX** [comment]
> and also `An annotation argument must be a compile-time constant`

Iirc you can use []

**Comment by bogadana** [comment]
> could you PR a proper implementation?

Annotation parameters cannot have nullable types, because the JVM does not support storing null as a value of an annotation attribute. (from https://kotlinlang.org/docs/annotations.html)

**Comment by bogadana** [comment]
oh yeah that i can do

**Comment by bogadana** [comment]
empty array results in 
`WARNING: Skipping enable-debugging: Incompatible with com.google.android.youtube. This patch is only compatible with`

**Pull request merged**
