### PR TITLE
feat: `swipe-controls` rewrite

### LINKED ISSUE #2379: swipe-controls takes too much control over brightness
In my opinion, this patch overrides the system's brightness control way more than it should.
I used patches release 2.9.4

**Reproduce:**
1. use fenster-swipe-controls patch
2. open a video
3. switch to full-screen view -> Video starts playing with system's brightness setting
4. swipe upwards on left side of phone screen to change brightness -> overrides the system's brightness (as it should)

**Observed behaviour**
When exiting full screen, exiting the video, or even when exiting the app (with video continuing to play in popup window), brightness control is not given back to the system, brightness can only be changed when going back into a video on full screen and adjusting brightness via swiping.

Brightness control is only given back to the system when ReVanced is closed entirely, or when the popup-window with the video is closed.

**Expected behaviour**
Better behaviour would be to only override system brightness when the video is played in full screen, and give back brightness control to the system as soon as user exits fullscreen

### LINKED ISSUE #2380: swipe-controls patch disables pinch to zoom to full extent
I have noticed that the fenster-swipe-controls patch makes it impossible to pinch to zoom to full display extent.
I used patches release 2.9.4

**Reproduce:**
1. Use a phone that has a screen aspect ration > 16:9 (e.g. 18:9)
2. use fenster-swipe-controls patch
3. open a video with 16:9 aspect ratio
4. switch to full-screen view
5. pinch to view the video on the entire phone screen (without black areas left and right)

**Expected behaviour**
Video zooms to cover entire screen

**Actual behaviour**
Nothing happens

### PR DESCRIPTION
**Pull request by shadow578**
see https://github.com/revanced/revanced-integrations/pull/64

### CODE REVIEW

**Comment by shadow578** [comment]
Btw, is there something i have to do / can do about the merge conflict? resolve button is grayes out for me

**Comment by Sculas** [comment]
Could you give us access to the PR? You can do so by enabling this checkbox on the right.
image

**Comment by Sculas** [comment]
> Btw, is there something i have to do / can do about the merge conflict? resolve button is grayes out for me

You have to do it manually in your IDE or using the Git command line because the merge conflict is too "big" for GitHub to fix by itself, I assume.

**Comment by shadow578** [comment]
> Could you give us access to the PR? You can do so by enabling this checkbox on the right.

is checked now

**Comment by TheJeterLP** [comment]
Merge conflicts fixed, is this ready?

**Comment by TheJeterLP** [comment]
Thanks for this awesome contribution again!

**Comment by TheJeterLP** [comment]
I have seen that the hdr-max-brightness patch is no longer working. It does not set the brightness to 100% on Fullscreen mode. Can you have a look into that?

**Comment by TheJeterLP** [comment]
See #150 for further information

**Pull request merged**
