### PR TITLE
feat(tiktok): remove compatibility version constraints

### LINKED ISSUE #2254: bug: TikTok Failing to patch with the latest patches.
### Type

Error while patching

### Bug description

Failing to patch properly TikTok with default (recommended) patches.
Some patches fail.

- ReVanced Manager Version: **1.3.0**
- Patches Version: **v2.174.0**
- Integrations Version: **v0.108.0**
- TikTok Version: Suggested **27.8.3**

**Logs:**
- [TikTok.log](https://github.com/revanced/revanced-patches/files/11561434/TikTok.log)

### Steps to reproduce

- Open ReVanced Manager
- Select TikTok app
- Select Default (Recommended) patches
- Patch
- Fail

### Relevant log output

```shell
TikTok Logs:

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.patchOptionNameAndOnClickEvent(SettingsPatch.kt:119)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:54)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:29)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!
```

### Screenshots or videos

TikTok 1
TikTok 2
TikTok 3

### Solution

_No response_

### Additional context

I opened this as a new issue only for TikTok as you told me [here](https://github.com/revanced/revanced-patches/issues/2245).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by kazimmt**
Closes ReVanced/revanced-patches-template#892

### CODE REVIEW

**Comment by kazimmt** [comment]
@oSumAtrIX when you're free
Please review & improve my errors 💗

**Comment by oSumAtrIX** [comment]
Made some refactoring changes. Please review if everything still works correctly.

**Comment by kazimmt** [comment]
> Made some refactoring changes. Please review if everything still works correctly.

I test 3 different version
27.8.3, 28.7.4, 29.7.4
All version working without any issues

**Review by oSumAtrIX — APPROVED** [review]

**Comment by TheJeterLP** [comment]
> > Made some refactoring changes. Please review if everything still works correctly.
> 
> I test 3 different version
> 27.8.3, 28.7.4, 29.7.4
> All versions are working without any issues

Show seek bar patch doesn't work on 29.7.4 for me. Patch applies fine, but seekbar doesn't show.

**Comment by kazimmt** [comment]
> Show seek bar patch doesn't work on 29.7.4 for me. Patch applies fine, but seekbar doesn't show. See #2338

`show-seekbar` patch wasn't modified in this PR. version constraints for this patch was removed a long time ago.
But yes, this patch also needs improvement.

**Comment by TheJeterLP** [comment]
> `show-seekbar` patch wasn't modified in this PR. version constraints for this patch was removed a long time ago.
> But yes, this patch also needs improvement.

Yes I've noticed, that's why I've created an issue for it

**Comment by samaraboy** [comment]
Hello, team. The patcher for tiktok above version 30.0.1 does not work.

**Comment by oSumAtrIX** [comment]
@samaraboy Open an issue

**Pull request merged**
