### PR TITLE
feat: bump youtube version to 17.33.42

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Iirc there were some issues such as #282 or #396. Have these been adressed in this PR?

**Comment by Canny1913** [comment]
> Iirc there were some issues such as #282 or #396. Have these been adressed in this PR?

can't reproduce the first
but yeah i just noticed wide search bar doesn't work
will look into it

**Comment by oSumAtrIX** [comment]
I can reproduce not being able to disable the seekbar tapping via the settings, maybe the patch is patching the bytecode at the wrong offset and thus ignoring the setting.

**Comment by Canny1913** [comment]
> I can reproduce not being able to disable the seekbar tapping via the settings, maybe the patch is patching the bytecode at the wrong offset and thus ignoring the setting.

will look into that aswell

**Comment by oSumAtrIX** [comment]
Thank you very much.

**Comment by Canny1913** [comment]
@oSumAtrIX You can merge this now.

**Comment by oSumAtrIX** [comment]
Thank you very much!

**Pull request merged**
