### PR TITLE
feat(YouTube): `default-video-quality` patch

### PR DESCRIPTION
**Pull request by johnconner122**
depends on:

 - https://github.com/revanced/revanced-integrations/pull/225

**TODO:**

- [x] ReVanced/revanced-patches-template#1311

### CODE REVIEW

**Comment by Mohammed1520** [comment]
When will it be released? 😅😅

**Comment by SodaWithoutSparkles** [comment]
Any progress?

**Comment by dekhu48** [comment]
will this ever get merged

**Comment by Ushie** [comment]
> will this ever get merged

It's labeled as Draft, meaning the pull request is not ready to be merged

**Comment by oSumAtrIX** [comment]
Superseded by #1880

**Pull request closed without merging**
