### PR TITLE
fix(youtube/theme): use custom light/dark colors for launch splash screen

### LINKED ISSUE #829: bug(youtube/theme): dark mode splash screen uses stock grey background color, and not the background color specified in theme options
### Type

Cosmetic

### Bug description

The splash screen of the youtube revanced app is grey instead of black. This is happening after the last update.

### Steps to reproduce

Step 1. Close & clear the youtube revanced from the ram.
Step 2. Open the app again
Step 3. Notice the color of the splash screen, i.e grey instead of black.

### Relevant log output

```shell
.
```

### Screenshots or videos

Screenshot_2023-06-01-12-35-47-61_64ef5fc2000c1caa954c114bb372e1d5

### Solution

_No response_

### Additional context

Patch version v2.175.0
Revanced manager version 1.3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by LisoUseInAIKyrios**
Use the same light/dark mode custom colors for the splash screen.

fixes https://github.com/revanced/revanced-patches/issues/2336

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
The patch option to provide a custom splash screen color can be removed. Instead the theme patch should simply provide a dark and light theme background color. This way, the user can chose a dark and light theme color and also expect the splash screen background color to change accordingly

**Comment by 0xrxL** [comment]
Dynamic Light/Black:

```?android:attr/textColorPrimaryInverse```

😉

**Comment by oSumAtrIX** [comment]
Won't work with custom colors.

**Comment by 0xrxL** [comment]
> Won't work with custom colors.

So you need to create a reference for the same field (with different color) inside ```values/ styles.xml``` at ```Base.LaunchScreen.Light``` and ```Base.LaunchScreen.Dark```

And you'll get custom color separately for light and dark theme.

**Comment by oSumAtrIX** [comment]
The PR already does this.

**Comment by 0xrxL** [comment]
> The PR already does this.

Oh...I didn't noticed them in the code, sorry.

**Pull request merged**
