### PR TITLE
fix: color download button

### LINKED ISSUE #407: bug: YouTube: Wrong reversed color of various button and notifications
### Type

Cosmetic

### Bug description

Download button is shown as dark in light mode while it should be white all the time. Notification saying applied quality is shown invertly to the appearance mode.

Screenshot_20220830-223415_YouTube
Screenshot_20220830-223705_YouTube
Screenshot_20220831-211511_YouTube

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Screenshots or videos

_No response_

### Solution

-

### Additional context

YouTube version 17.32.38

### PR DESCRIPTION
**Pull request by Titivoot**
Closes ReVanced/revanced-patches-template#2210.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Can you reference the issue?

**Comment by Titivoot** [comment]
> Can you reference the issue?

https://github.com/revanced/revanced-patches/issues/407#issue-1356220805

**Comment by oSumAtrIX** [comment]
Does this respect both, light and dark mode?

**Comment by Titivoot** [comment]
> Does this respect both, light and dark mode?

I only edited the color of the download button

**Comment by anil-al** [comment]
In #407 I also talked of notifications showing applied quality having inverted colour. Is that also fixed?

**Comment by oSumAtrIX** [comment]
That is intended behaviour.

**Pull request merged**
