### PR TITLE
feat(twitch): add `chat/autoclaim` for automatically claiming Channel Points

### LINKED ISSUE #1043: feat(patch): Twitch chest clicker
### Application

Twitch

### Issue

QoL feature

### Patch

Autoclick when the green chest appears

### Motivation

No need to click when it appears, also feature parity with TwitchMod

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### LINKED ISSUE #1756: feat(twitch): `autoclaim-channel-points` patch
### Application

Twitch

### Issue

QoL feature

### Patch

Auto-Claim Bonus Channel Points

### Motivation

No need to click when it appears, also feature parity with TwitchMod

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by redphx**
PR for `revanced-intergrations`: https://github.com/revanced/revanced-integrations/pull/398

Closes ReVanced/revanced-patches-template#1756. 
Tested on Twitch 14.6.1.

### CODE REVIEW

**Comment by redphx** [comment]
> Could this be added to the Twitch ReVanced settings? So it can be enabled/disabled in app?

Didn't know it was a thing. Let's me try.

**Comment by redphx** [comment]
Hi @LisoUseInAIKyrios, I've updated the code.  
Please check, thank you.

**Comment by redphx** [comment]
@oSumAtrIX I used "Channel Points" instead of "channel points" because it's the official name from Twitch: https://blog.twitch.tv/en/2019/12/16/channel-points-an-easy-way-to-engage-with-your-audience/

**Comment by oSumAtrIX** [comment]
I didn't know that it is considered a name. In that case, please open a follow up PR to fix the naming please, thanks.

**Comment by redphx** [comment]
@oSumAtrIX done #2138

**Pull request merged**
