### PR TITLE
feat(trakt): add `unlock-pro` patch

### PR DESCRIPTION
**Pull request by johnconner122**
closes: ReVanced/revanced-patches-template#933

### CODE REVIEW

**Comment by kazimmt** [comment]
`methodDef, _ ->`
fails but

`methodDef ->`
pass
idk why

**Comment by johnconner122** [comment]
> `methodDef, _ ->` fails but
> 
> `methodDef ->` pass idk why

probably patcher version difference

**Comment by kazimmt** [comment]
Yes, you're right.
Now it's working

**Comment by YashjitPal** [comment]
What happened?

**Comment by YashjitPal** [comment]
> > `methodDef, _ ->` fails but
> > 
> > `methodDef ->` pass idk why
> 
> probably patcher version difference

How can I use this patch?

**Comment by YashjitPal** [comment]
> Yes, you're right.
> Now it's working

How can I use it?

**Comment by johnconner122** [comment]
> > Yes, you're right.
> > Now it's working
> 
> How can I use it?

Wait until it's release.

**Comment by YashjitPal** [comment]
> > > Yes, you're right.
> > > Now it's working
> > 
> > How can I use it?
> 
> Wait until it's released. 

I'm new to this. Can you tell me how long it can take?

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
