### PR TITLE
refactor: settings component abstraction

### PR DESCRIPTION
**Pull request by timschneeb**
This PR attempts to centralize the settings components and moves code for creating XML nodes into the component classes instead of handling it inside `SettingsResourcePatch`.

### CODE REVIEW

**Comment by johnconner122** [comment]
Can you please implement the List Preference?

**Comment by ThePBone** [comment]
> Can you please implement the List Preference?

Sure. I need ListPreference (and PreferenceCategory) for my Twitch settings patch as well.

**Comment by oSumAtrIX** [comment]
Made some refactoring changes, please review if everything is correct and we can get it merged, thanks.

**Comment by ThePBone** [comment]
Looks good to me; it can be merged.

**Pull request merged**
