### PR TITLE
general ads refactor, new patches

### LINKED ISSUE #326: feat: extended litho elements block
### Type

Cosmetic

### Issue

The current litho view blockage is incomplete, and based solely on container-type templates.

To be more specific:

Each litho view is composed of multiple elements. For example: a `buttons bar` is a container, inside which there will be other containers of type `button`, which in turn will contains other elements of type `image icon` and `textbox`.

Well...following the aforementioned example, we are currently able to block just the `buttons bar` and not the child elements (entire button or its icon/textbox).

### Feature

The same bytecode method related to ads blocking, re-fill the SAME bytebuffer and template name variables with other informations, before performing a `return-object`.

These informations are related to every child elements of every main container.

### Motivation

To block further elements without hide the entire parent object.

### Additional context

Add the following bytecode patch before the last `if-nez`, followed by `return-object`:

```
move-object/from16 v1, p2
invoke-virtual {v1}, Ljava/lang/Object;->toString()Ljava/lang/String;
move-result-object v1
move-object/from16 v2, p3
iget-object v2, v2, {byteBufferClassRegister};->b:Ljava/nio/ByteBuffer;
invoke-static {v1, v2}, YourCopiedLithoADSBlockClass;->YourCopiedLithoADSBlockMethod(Ljava/lang/String;Ljava/nio/ByteBuffer;)Z
move-result v2
if-eqz v2, :cond_removeactionbarbutton
const/4 v0, 0x0
:cond_removeactionbarbutton
```

### PR DESCRIPTION
**Pull request by ghost**
Closes #326, #301, #108, #167, #295.

TODO:

- [x] Separate hiding info cards and end screen to separate patches
- [x] Add missing toggles in the settings for info cards and end screen removal
- [ ] Refactor the  `NewGeneralPatch` class to remove duplicates and easily break code by using opcode patterns in fingerprints.
- [x] Properly name `NewGeneralPatch` patch to `GeneralAdsRemovalPatch`

RE: https://github.com/revanced/revanced-integrations/pull/161

### CODE REVIEW

**Comment by inotia00** [comment]
`hide-reels` patch does not need to be added to [`GeneralAdsRemovalPatch`](https://github.com/revanced/revanced-patches/pull/641/commits/6457786aa5069e7242de9f00ff8fba296c79ec25#diff-48182a309dc212b402943fd71c47b327fbf66b5392ebd5a5e70d9d008b275512)

[`HideReelsPatch`](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/reels/patch/HideReelsPatch.kt) already exists, just that it is not declared as a patch (only `@Patch` is missing)

**Comment by OxrxL** [comment]
Patch is now fully working!

**Comment by Angelol125** [comment]
I don't want to sound like a judging dick about it, but I really am curious as to why hasn't this been merged yet.. Also, and I hope this goes without saying, I, and I hope the rest of the community appreciates your wonderful work you've put into this after vanced was discontinued.

**Comment by OxrxL** [comment]
> I don't want to sound like a judging dick about it, but I really am curious as to why hasn't this been merged yet.. Also, and I hope this goes without saying, I, and I hope the rest of the community appreciates your wonderful work you've put into this after vanced was discontinued.

@oSumAtrIX

**Comment by Angelol125** [comment]
Thank you, I appreciate the quick response @OxrxL.

**Comment by OxrxL** [comment]
> Thank you, I appreciate the quick response @OxrxL.

No problem. This patch is ready and working however (if you want to use it).

For further explanations: wait the answer of oSum.

**Comment by oSumAtrIX** [comment]
The PR is not ready yet as seen in the PR descriptions todo section.

**Pull request closed without merging**
