### PR TITLE
fix(Remove screenshot restriction): Improve reliability

### PR DESCRIPTION
**Pull request by Linus789**
issue: ReVanced/revanced-patches-template#651
integrations: https://github.com/ReVanced/revanced-integrations/pull/471

@gthu34 could you check if this fixes your issue?

### CODE REVIEW

**Comment by Linus789** [comment]
@LisoUseInAIKyrios I'm not able to test if this PR fixes the problem, because my ROM ignores all screenshot restrictions by default.

**Comment by oSumAtrIX** [comment]
Is this PR still active? If so, mark as ready for review.

**Comment by Linus789** [comment]
The PR is still active, I just have to find some time to test it.

**Comment by Linus789** [comment]
Okay, I just tested it with Telegram and it seems to work. So it should close #2570.

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
