### PR TITLE
fix(youtube/teme-patch): app theme setter fingerprint

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
What does this PR do?

**Comment by oSumAtrIX** [comment]
Can you attach a recording of doing the following without applying this fix:

1. Ensure you set dark mode on Android
2. Enable light mode in YouTube settings
3. Visit the ReVanced settings

**Comment by OxrxL** [comment]
Forgive me for the forced push, but was necessary.

**Comment by OxrxL** [comment]
> Can you attach a recording of doing the following without applying this fix:
> 
> 1. Ensure you set dark mode on Android
> 2. Enable light mode in YouTube settings
> 3. Visit the ReVanced settings

https://www.veed.io/view/c44ec734-8a98-4bd0-933a-38f194ce0075

**Comment by OxrxL** [comment]
YouTube it behaves differently according to the state of the app (fresh start or with already existing app data).

So...we need to add two additional setTheme() method calls at 2 different indexes.

That's all.

**Comment by oSumAtrIX** [comment]
Is the phone set to dark mode?

**Comment by OxrxL** [comment]
> Is the phone set to dark mode?

Yes.

**Review by oSumAtrIX — APPROVED** [review]

**Comment by kairusds** [comment]
#943

**Pull request merged**
