### PR TITLE
feat(youtube): add `Player Flyout Menu` patch

### PR DESCRIPTION
**Pull request by johnconner122**
closes: ReVanced/revanced-patches-template#1968, ReVanced/revanced-patches-template#1805

depends on:

- https://github.com/revanced/revanced-integrations/pull/416

### CODE REVIEW

**Review by oSumAtrIX — APPROVED** [review]
Looks good 👍 The integrations code also looks ready but is marked as a draft, is that intentional?

**Comment by johnconner122** [comment]
> but is marked as a draft, is that intentional?
 It's has TODO's `(remove bug and testing)`

**Comment by johnconner122** [comment]
Accidental click for review 😬

**Review by oSumAtrIX — APPROVED** [review]

**Comment by johnconner122** [comment]
@oSumAtrIX On side note some patch depend on `LithoFilterPatch`, if user doesn't select on of those patches, patches the app, then components will still be filtered. We should add a check or change `SettingsEnum` values to `false` and change their default values in patch class if included.

**Comment by oSumAtrIX** [comment]
This is known. Instead, a hook should be added for each patch.

**Comment by johnconner122** [comment]
> Could this also hide the new "add to play next queue"?

Theatrically, yes. If you know component's name.

**Comment by johnconner122** [comment]
@LisoUseInAIKyrios this PR is not implementing #2167, why did you link the issue?

**Comment by johnconner122** [comment]
> Is this ready to merge?

*YES*

**Pull request merged**
