### PR TITLE
fix(tiktok/fingerprint): update 'feedfilter' and 'settings' fingerprints to new version

### PR DESCRIPTION
**Pull request by d4rkk3y**
update outdated fingerprints.

### CODE REVIEW

**Review by FineFindus — COMMENTED** [review]
Do the new fingerprints still work with the older app versions?

**Comment by d4rkk3y** [comment]
> Do the new fingerprints still work with the older app versions?

No. It doesn't. Is it better to add version to Compatibility annotations?

**Comment by oSumAtrIX** [comment]
If you are unsure if the patch will work for future versions, add the annotation, if you think it will remain to work, don't.

**Comment by d4rkk3y** [comment]
sorry I create PR to wrong branch.

**Comment by oSumAtrIX** [comment]
You can change the target branch on GitHub by clicking on `edit`.

**Review by oSumAtrIX — COMMENTED** [review]
Are you sure the fingerprints will work with future versions?

**Comment by d4rkk3y** [comment]
> Are you sure the fingerprints will work with future versions?

No, I am not. Because recently I notice that the settings patch's fingerprint change. For example, the last time you update settings fingerprint but now it changed. So I add version to patches depend on settings patch too.

**Review by oSumAtrIX — APPROVED** [review]

**Comment by TheJeterLP** [comment]
This does not work. See #1487

**Pull request merged**
