### PR TITLE
feat: custom music branding

### PR DESCRIPTION
**Pull request by FineFindus**
Closing ReVanced/revanced-patches-template#1849 by adding custom branding to music.

The patch is based on the `custom-branding` patch for YouTube. It currently uses the same icons, since I couldn't find a revanced music icon. If someone could point me to one, I would swap them out.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Instead of duplicating the code, you should simply create a shared patch by adding the YouTube Music package name to the compatibility annotation.

**Comment by FineFindus** [comment]
Reworked it. I'm sorry if this is not idiomatic Kotlin, this is my first time writing something in it. I tried to keep the option to change the app name and the icon for both apps, even though they will still be using the same icon.

**Comment by FineFindus** [comment]
Ah, I understand now what you meant in [your previous comment](https://github.com/revanced/revanced-patches/pull/915#issuecomment-1296333991). Currently, the patch does not work, because `context.copyResources("branding", it)` does not change the icon file name. Should I duplicate the `context.copyResources()` function to be able to change the file name? I'm asking since you didn't seem too happy with duplicated code last time.

**Comment by oSumAtrIX** [comment]
Introducing a new specifically adjusted `copyResources` method shouldn't be done just for this patch. I am not sure myself yet how to implement it.

**Comment by FineFindus** [comment]
Since the logo submission is ending soon, and a new logo will be chosen, I would suggest to wait with this pr until the vote is over. I'm guessing that after the vote, YT Music will have a different logo than the YouTube App, so a refactor with different logos would be needed, which might make this patch without duplicated code easier.

**Comment by oSumAtrIX** [comment]
I can not commit to your branch because the fork has attached to a different repository. To be able to fix this, I will need explicit push access to your fork repository.

**Comment by FineFindus** [comment]
What do you need to change? Since my repo is currently not based on the revanced repo, I will rebase it onto this repo, including this pull request, in the near future

**Comment by oSumAtrIX** [comment]
I do not suggest rebasing because that will likely make numerous conflicts. There are specific changes I can make to properly fix the branch.

**Comment by oSumAtrIX** [comment]
Your repository does not fork from ours, which is why this PR can not work. Please delete your remote repository after pulling my changes from it to local. Afterwards fork this repository again and force push the local branch to it again. Reopen the PR.

**Comment by FineFindus** [comment]
I followed the steps, but I can't reopen the pr.

**Comment by oSumAtrIX** [comment]
After you create a fork of this branch in a new repository, open it here

**Pull request closed without merging**
