### PR TITLE
ReturnYouTubeDislike patch fix

### PR DESCRIPTION
**Pull request by LisoUseInAIKyrios**
patch adjustment for latest YouTube

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
This PR is not fixing anything as this repository targets the latest revanced-patcher version which can resolve fingerprints on sub-string references. Context: https://github.com/revanced/revanced-patches/issues/1309#issuecomment-1357031863.

**Comment by LisoUseInAIKyrios** [comment]
A cli release should be published soon, as currently RYD is broken if patching with the manager using it's default settings.

**Comment by oSumAtrIX** [comment]
Releases are figured by semantic release. We can't force release a version unless theres a releasing commit. You could make a PR to fix some generic issue or improve performance or similar which would trigger release.

**Comment by LisoUseInAIKyrios** [comment]
https://github.com/revanced/revanced-patcher/commit/c5de9e29889dffd18b31e62a892881cc48e8b607

If this change is merged into the main branch and a released is published, then RYD would work again when patching using the manager.

**Comment by oSumAtrIX** [comment]
This commit is already available in this release: https://github.com/revanced/revanced-patcher/releases/tag/v6.3.2.
The patches use this version. The CLI does too in the latest commit, but is not released yet.

**Comment by LisoUseInAIKyrios** [comment]
Ok so the problem is not affecting the official manager, buy instead only when building on command line.

Although that includes 3rd party (unsupported) tools to build ReVanced.

**Comment by oSumAtrIX** [comment]
3rd party is out of our reach. There is no problem, the CLI is just missing a release.

**Pull request closed without merging**
