### PR TITLE
feat: `compact-header` patch

### PR DESCRIPTION
**Pull request by ponces**
This patch is excluded by default.
Based on Vanced's work.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Thanks, fyi the root variant for YouTube Music is fixed now.

**Comment by ponces** [comment]
> Thanks, fyi the root variant for YouTube Music is fixed now.

How??

**Comment by oSumAtrIX** [comment]
The alignment of, the zip entries for libraries is now done properly (4KiB).

**Comment by ponces** [comment]
Same issue with missing library after all 😞

**Comment by Canny1913** [comment]
Aligning is still broken :D

**Pull request merged**
