### PR TITLE
fix: `codecs-unlock` patch and update Music patches to `5.14.53`

### PR DESCRIPTION
**Pull request by ponces**
It's working now 👍 

Screenshot_20220714-231528_Pixel Launcher

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Have you confirmed with multiple videos?

**Comment by ponces** [comment]
> Have you confirmed with multiple videos?

One or two did not have a better codec available but I believe this patch depends on the video/audio and device as its author stated in the description...
https://user-images.githubusercontent.com/4687488/179216275-628776b0-e4dc-4b28-8728-e9f735b37b91.mp4

**Comment by ponces** [comment]
I'll make a final push to also update the version from the ads patch ok?
Thanks!

**Comment by oSumAtrIX** [comment]
Sure.

**Comment by ponces** [comment]
I'm not sure if this is mergeable as it is as I had to include the music-video-ads patch as I didn't have it on this branch.
If not, then you can close this and i'll open a new PR with a clean commit history...

**Comment by ponces** [comment]
New [PR](https://github.com/revanced/revanced-patches/pull/183) pushed!
Thanks!

**Pull request closed without merging**
