### PR TITLE
feat: `swipe-controls` patch

### PR DESCRIPTION
**Pull request by shadow578**
Adds video swipe controls (aka `FensterV2`) that enable the user to change volume and screen brightness by swiping. 

| UI Overlay | 
| ------- | 
| big-bunny | 

see accompanying integration pr https://github.com/revanced/revanced-integrations/pull/50

### CODE REVIEW

**Comment by TheJeterLP** [comment]
So I just tried it out and the Patch did not work for me. Nothing happened at all.

**Comment by TheJeterLP** [comment]
@shadow578 could you please fix the issues this patch has?

**Comment by TheJeterLP** [comment]
> This seems to work, both brightness and volume. The way it is intended to work am not sure though. You have to long press on the left/right side and then swipe up/down to make it work

Does not work for me.

**Comment by gvijayakumar-16** [comment]
`java -jar revanced-cli-2.3.2-all.jar --experimental \
 -a youtube_17.25.35.apk \
 -c \
 -d deviceId \
 -o revanced.apk -m app-release-unsigned.apk \
 -b revanced-patches-2.9.0.jar`

This is the command I had executed (Note for all the versions I had used) for non-root. Also, the commit was tested with `17.24.34` This was mentioned in commit file changes

**Comment by shadow578** [comment]
> could you please fix the issues this patch has?

sorry, didn't get any notificatons on this particular PR. But can i even push further commits into this PR now that it was merged?  Or should i create a new branch & PR?

Although only issue i'm seeing is `injectIntoNamedMethod` which seems like it can actually be removed and replaced with a custom fingerprint


> This seems to work, both brightness and volume. The way it is intended to work am not sure though. You have to long press on the left/right side and then swipe up/down to make it work

this is correct. See https://github.com/revanced/revanced-integrations/pull/50 for a more detailed write- up. 
You have to long- press into one of the zones (around 1/3rd of the screen, from the left and right edge) until you get a haptic feedback. After this, you'll be able to swipe up and down to adjust the volume and brightness.

> This is the command I had executed (Note for all the versions I had used) for non-root. Also, the commit was tested with 17.24.34 This was mentioned in commit file changes

correct. I don't have the resources to test more versions, so i kept the compatibility at `17.24.34` since that's the version i'm using for development. Tbh there shouldn't be anything stopping the patch from working on more versions, since i'm mostly hooking into functions that the youtube devs cannot easily change

**Comment by TheJeterLP** [comment]
> > could you please fix the issues this patch has?
> 
> sorry, didn't get any notificatons on this particular PR. But can i even push further commits into this PR now that it was merged?  Or should i create a new branch & PR?
> 
> Although only issue i'm seeing is `injectIntoNamedMethod` which seems like it can actually be removed and replaced with a custom fingerprint
> 
> 
> > This seems to work, both brightness and volume. The way it is intended to work am not sure though. You have to long press on the left/right side and then swipe up/down to make it work
> 
> this is correct. See https://github.com/revanced/revanced-integrations/pull/50 for a more detailed write- up. 
> You have to long- press into one of the zones (around 1/3rd of the screen, from the left and right edge) until you get a haptic feedback. After this, you'll be able to swipe up and down to adjust the volume and brightness.
> 
> > This is the command I had executed (Note for all the versions I had used) for non-root. Also, the commit was tested with 17.24.34 This was mentioned in commit file changes
> 
> correct. I don't have the resources to test more versions, so i kept the compatibility at `17.24.34` since that's the version i'm using for development. Tbh there shouldn't be anything stopping the patch from working on more versions, since i'm mostly hooking into functions that the youtube devs cannot easily change
> 
> 

Long pressing does not work for me on my OnePlus 10 pro using YouTube 17.25.34. 
Please create a new PR from your existing branch.

**Comment by TheJeterLP** [comment]
Will send a screen record later

**Comment by TheJeterLP** [comment]
Also I dont like the idea of having to hold first. Could you please change it so it works like in original vanced?

**Comment by shadow578** [comment]
> Also I dont like the idea of having to hold first. Could you please change it so it works like in original vanced?

i'll add a setting to enable or disable the feature. I'm working on a fix for https://github.com/revanced/revanced-patches/issues/121 at the moment anyway, so it won't be much effort.

**Comment by TheJeterLP** [comment]
> > Also I dont like the idea of having to hold first. Could you please change it so it works like in original vanced?
> 
> i'll add a setting to enable or disable the feature. I'm working on a fix for #121 at the moment anyway, so it won't be much effort.

see https://youtu.be/RtbHBcMmnFc for my screen record.

**Comment by TheJeterLP** [comment]
Please create a new PR for this with the addition of 17.25.34 version :)

**Comment by shadow578** [comment]
just a quick heads- up about the fix, just opened the pull request https://github.com/revanced/revanced-integrations/pull/61

**Pull request merged**
